CREATE TABLE FOODTRUCK
(
  LOCATION_ID INT PRIMARY KEY,
  CNN INT,
  BLOCKLOT INT,
  BLOCK INT,
  LOT INT,
  X FLOAT(12,2),
  Y FLOAT(12,2),
  LATITUDE DOUBLE(14,2),
  LONGITUDE DOUBLE(14,2),
  RECEIVED INT,
  PRIOR_PERMIT INT
) 
AS 
SELECT * 
FROM CSVREAD('F:\NidhiProjects\SpringProject\springrestfoodservice');